### ISSUE TITLE
Er is nogal wat mis met het modaal

### ISSUE THREAD

**Issue by Theo-denBlanken** [RobbeLee/modaal#1]
Je hebt feedback gekregen van **Theo-denBlanken**
URL: https://github.com/RobbeLee/modaal/blob/master/

Feedback: padding ontbreekt[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"reviewer":"Theo-denBlanken"}')

**Comment by RobbeLee** [comment]
Beste Theo,
De CSS is aangepast en nu zit er ook padding in.
