### ISSUE TITLE
Er is nogal wat mis met het modaal

### ISSUE THREAD

**Issue by Theo-denBlanken** [RobbeLee/modaal#2]
Je hebt feedback gekregen van **Theo-denBlanken**
URL: https://github.com/RobbeLee/modaal/blob/master/

Feedback: las je erop klikt sluit het, ook bij een klik naast de sluitknop[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"reviewer":"Theo-denBlanken"}')

**Comment by RobbeLee** [comment]
Heb ook dit probleem opgelost, zie de commits.
