### ISSUE TITLE
sluitknop

### ISSUE THREAD

**Issue by Theo-denBlanken** [RobbeLee/modaal#3]
Je hebt feedback gekregen van **Theo-denBlanken**
URL: https://github.com/RobbeLee/modaal/blob/master/

Feedback: kan naar een andere positie[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"reviewer":"Theo-denBlanken"}')

**Comment by RobbeLee** [comment]
Sluitknop staat nu op de juiste plaats (rechtsboven).
